### PR TITLE
Separate templates from real content

### PR DESCRIPTION
**Pull request by tomschr**
This PR contains:

* a new directory `templates`
* a short `README.md` inside `templates` for describing the folder (maybe not needed?)
* a correction of the paths to the templates in the root `README.md`
* move the template DC files into `templates` (to make CI happy)

Reasons:

* Avoids confusion in `xml/` folder
* Separation of concerns

### CODE REVIEW

**Review by taroth21 — APPROVED** [review]
LGTM, many thanks! 

Let's ask @sknorr to have a look, too.

**Comment by sknorr** [comment]
Separating makes sense.

I wonder about the big picture(tm) though. What parts of the template should be in `doc-kit` or do we not want to use `doc-kit` for this repo at all (anymore)? Granted, that topic is not entirely--I should probably have asked before #1 was merged. :)

**Comment by taroth21** [comment]
> Separating makes sense.
> 
> I wonder about the big picture(tm) though. What parts of the template should be in `doc-kit` or do we not want to use `doc-kit` for this repo at all (anymore)? Granted, that topic is not entirely--I should probably have asked before #1 was merged. :)

It's still my plan to use doc-kit for this repo, if possible (see https://jira.suse.com/browse/DOCTEAM-253). Good reminder that I need to finish my WIP PR https://github.com/openSUSE/doc-kit/pull/30.

**Comment by sknorr** [comment]
But then, if we only want the entities in doc-kit and keep the rest of the template here, we can remove most of files from your doc-kit PR. (?)

**Comment by tomschr** [comment]
Thanks for all!

**Pull request merged**
