### PR TITLE
Vistatec/sle 15 sp6 locdrop3 doc modular localisation checkin

### PR DESCRIPTION
**Pull request by ptinley-vt**
### Description

Delivering the localised Minimal VM (in bigfile format) for ZH-CN.

**NOTE:** The book is named as 'SLES Minimal VM Quick Start' in the instructions to localise, but the actual title is 'Introduction to SLES Minimal VM'.

1 book, 1 target language (zh-cn)

I hope this is the correct place to deliver.

### CODE REVIEW

**Review by jfaltenbacher — APPROVED** [review]
LGTM!

**Comment by jfaltenbacher** [comment]
Files were checked with:
- optipng (no images)
- daps validate
- visual spot check of PDF

The only issue is that the image folder is missing, the folder is required by daps. Either the folder is added or the line is removed from DC file - I am unsure which would be the most suitable solution. 

Everything else is fine from my side and good to be published

**Comment by ptinley-vt** [comment]
Thanks Julia.

I have an empty 'images' directory on my local repository, where I tested the files. I had to create it the other day because ``daps validate`` would not work. I didn't realise is was governed by the reference in the DC file.

I suppose, since there are no images in this book, it make sense to comment there reference out of the DC file.

**Comment by taroth21** [comment]
@ptinley-vt and @jfaltenbacher : Commenting the reference in the DC file would work but if we ever add more articles in to `zh-cn` and some of them actually have images, we need to add the `images`  directory anyway sooner or later. Hence, I did so now (I used the 'trick' to add a hidden `.gitkeep` file to the empty directory, otherwise you cannot add and push an empty directory to git). 

I build a PDF again afterwards : `daps` no longer complains and everything should be fine.

**Review by taroth21 — APPROVED** [review]
LGTM, thanks

**Comment by jfaltenbacher** [comment]
PR merged. It needs to be discussed how the guide can be added to docserv-config in order to be published

**Comment by taroth21** [comment]
@jfaltenbacher : see [link to GitLab PR](https://gitlab.suse.de/susedoc/docserv-config/-/merge_requests/976)

**Pull request merged**
